addpath('..\SRC')
addpath(genpath('..\..\COMH'))
addpath(genpath('..\..\MAPH'))
addpath(genpath('..\..\MOTH'))
addpath(genpath('..\..\MOVH'))
addpath(genpath('..\..\POSH'))
addpath(genpath('..\..\ROTH'))
addpath(genpath('..\..\SCAN'))
addpath(genpath('..\..\DSCA'))
addpath(genpath('..\..\MOMO'))
addpath(genpath('..\..\COML'))
ControlInit;
AreaCoverageCalib;
MotorConfigurationSheet;